# Generated by Django 3.2.9 on 2021-11-28 14:59

import django.contrib.postgres.fields
from django.db import migrations, models
import sudoku.models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_alter_sudoku_cells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudoku',
            name='cells',
        ),
        migrations.AddField(
            model_name='sudoku',
            name='grid',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=9), default=sudoku.models.empty_grid, size=9),
        ),
    ]
